**DATA TYPES**

1. Build-in Data types

*  Nonetype
*   NUmeric types
*   Sequences
*   sets
*  Mappings
2. numeric data type
*   int
*   float
*   complex
3.  coversion of one data type to another data type
4. Boolean datatype
5. sequences
*   str
*   bytes
*   byte array
*   list
*   tuple
*   range












In [ ]:
a=5
print(type(a))
a=-34
print(type(a))
a=90.09
print(type(a))
a=3+4j
print(type(a))
#conversion
a=10.0
print(int(a))
a=10
print(float(a))
a=10
b=5
print(complex(a))

# Boolean
a=3>6
print(a)


<class 'int'>
<class 'int'>
<class 'float'>
<class 'complex'>
10
10.0
(10+0j)
False


**LIST OPERATIONS**

1.  len()
1.   sum()
1.   max()
1.   min()
1.   index()
1.   count()
2.  reverse()
2.  sort()
2.  sort(reverse=True)
2.  append()
2.  insert()
2.  extend()
1.  remove()
2.  del()
1.  copy()












In [ ]:
#list operations
#empty list
l=[]
l=[1,3,5,2,5,7,8,89]
print(list)
#indexing
print(l[0])
#slicing
print(l[0:6])
#len of the list
print(len(l))
#sum of the elements
print(sum(l))
#max ,min element
print(max(l))
print(min(l))
#index of an element
print(l.index(5))
#count of an element
print(l.count(5))
#reverse

#sort
print("sorted array")
print(sorted(l))
l.sort(reverse=True)
print(l)
#append()
print("appending an element")
l.append(90)
print(l)
#insert
print("insert at position")
l.insert(0,99)
print(l)
#entend

print("extend an element")
l1=[8,9]
l.extend(l1)
print(l)
#remove
print(l)
print("remove an element")
l.remove(8)
print(l)
print("remove last element")
print(l.pop())
print("remove element by position")
print(l.pop(6))
print("delete in range")
del l[0:]

<class 'list'>
1
[1, 3, 5, 2, 5, 7]
8
120
89
1
2
2
sorted array
[1, 2, 3, 5, 5, 7, 8, 89]
[89, 8, 7, 5, 5, 3, 2, 1]
appending an element
[89, 8, 7, 5, 5, 3, 2, 1, 90]
insert at position
[99, 89, 8, 7, 5, 5, 3, 2, 1, 90]
extend an element
[99, 89, 8, 7, 5, 5, 3, 2, 1, 90, 8, 9]
[99, 89, 8, 7, 5, 5, 3, 2, 1, 90, 8, 9]
remove an element
[99, 89, 7, 5, 5, 3, 2, 1, 90, 8, 9]
remove last element
9
remove element by position
2
delete in range


**STRING OPERATIONS**

1.   len()
2.   max()
3.   upper()
4.   lower()
5.   count()
6.   index()
7.   find() or replace()
8.   join()
9.   split()



In [ ]:
s="alluarjun"
print(s)
print("len of string")
print(len(s))
print("upper case")
print(s.upper())
print("lower case")
print("title= each word starting letter capital")
print(s.title())
print("count of char")
print(s.count("a"))
print("index of char")
print(s.index("a"))
print(s.find("l"))
print("replace char")
print(s.replace("ll","ss"))
s=" hlo world"
print("split a str")
a=s.split()
print(s.split())
print("join of str")
print("".join(a))



alluarjun
len of string
9
upper case
ALLUARJUN
lower case
title= each word starting letter capital
Alluarjun
count of char
2
index of char
0
1
replace char
assuarjun
['hlo', 'world']
join
hlo world


**Tuple operations**


1.   len()

1.   sum()

1.   max(),min()
2.   index()


5.   count()


6.   sorted()



In [ ]:
t=(1,25,7,8,4,84,86,45)
print("len of tuple")
print(len(t))
print("sum of elements")
print(sum(t))
print("min,max of tuple")
print(min(t))
print(max(t))
print("index of an element")
print(t.index(45))
print("count of an element")
print(t.count(45))
print("sorted tuple")
print(sorted(t))
print("sorted in descending order")
print(sorted(t,reverse=True))


len of tuple
8
sum of elements
260
min,max of tuple
1
86
index of an element
7
count of an element
1
sorted tuple
[1, 4, 7, 8, 25, 45, 84, 86]
sorted in descending order
[86, 84, 45, 25, 8, 7, 4, 1]


**Set operations**

INDEXING

add()

SLICING

UPDATE()

REMOVE()


In [ ]:
s={1,2,4,53,78,23}
s.add(90)
print(s)
s.update([98,57])
print(s)
print(s)
s.remove(53)
print(s)


{1, 2, 4, 53, 23, 90, 78}
{1, 2, 4, 78, 23, 90, 98, 53, 57}
{1, 2, 4, 78, 23, 90, 98, 53, 57}
{1, 2, 4, 78, 23, 90, 98, 57}


**Frozenset Dataset**



In [ ]:
s=frozenset("abcd")
print(s)

frozenset({'b', 'd', 'c', 'a'})


**OPERATIONS**
1. Arithmetic

2.   assignment


3.  unary  minus
4.  relational
5.   logical

6.  boolean

7.   membership
6. identity




In [ ]:
print("Arithmetic operations")
a=10
b=4
print(a*b)
print(a+b)
print(a-b)
print(a//b)
print(a%b)
print(a**3)


Arithmetic operations
40
14
6
2
2
1000


In [ ]:
print("Assignment operations")
a=10
a=a+3
print(a)
a-=3
print(a)

Assignment operations
13
10


In [ ]:
print("unary minus operator")
n=10
print(-n)


unary minus operator
-10


In [ ]:
print("Relational operators")
a=4
b=43
print(a>=5)
print

Relational operators
False
True
False
True


**control statements**
this are used to control the flow of the execution
if-else

In [ ]:

#if -else
a=9
if a%2==0:
  print("even")
else:
  print("odd")


#
k=55
for i in range(0,10):
  if k ==i:
    print("yes")
    break
else:
  print("no")

#if -elif --else
#positive or negative
a=10
if a>0:
  print("positive")
elif a==0:
  print("zero")
else:
  print("negative")


odd
no
positive


while loop
for loop **bold text**

In [ ]:
i=0
while(i<10):
  print(i)
  i=i+1


i=0
while(i>=0):
  print(i)
  i=i+1


Streaming output truncated to the last 5000 lines.
444214
444215
444216
444217
444218
444219
444220
444221
444222
444223
444224
444225
444226
444227
444228
444229
444230
444231
444232
444233
444234
444235
444236
444237
444238
444239
444240
444241
444242
444243
444244
444245
444246
444247
444248
444249
444250
444251
444252
444253
444254
444255
444256
444257
444258
444259
444260
444261
444262
444263
444264
444265
444266
444267
444268
444269
444270
444271
444272
444273
444274
444275
444276
444277
444278
444279
444280
444281
444282
444283
444284
444285
444286
444287
444288
444289
444290
444291
444292
444293
444294
444295
444296
444297
444298
444299
444300
444301
444302
444303
444304
444305
444306
444307
444308
444309
444310
444311
444312
444313
444314
444315
444316
444317
444318
444319
444320
444321
444322
444323
444324
444325
444326
444327
444328
444329
444330
444331
444332
444333
444334
444335
444336
444337
444338
444339
444340
444341
444342
444343
444344
444345
444346
444347
444348
4443

KeyboardInterrupt: 

In [ ]:
l=[1,2,3,4,6,5,56,33]
for i in range(0,len(l)):
  print(l[i])


1
2
3
4
6
5
56
33


nested loop


In [ ]:
l=[1,2,3,4]
i=0
while (i<len(l)):
  k=0
  while (k<l[i]):
    print(i)
    k=k+1
  i=i+1

0
1
1
2
2
2
3
3
3
3


break

In [ ]:
for i in range(0,10):
  if i==8:
    break
  else:
    print(i)

0
1
2
3
4
5
6
7


continue

In [ ]:
for i in range(0,10):
  if i==8:
    continue
  else:
    print(i)

0
1
2
3
4
5
6
7
9


pass

In [ ]:
for i in range(0,10):
  if i==8:
    pass
  else:
    print(i)

0
1
2
3
4
5
6
7
9


return statement

In [ ]:
def f(a,b):
  return a+b
a=10
b=20
print(f(a,b))

30


numpy

In [ ]:
import numpy as np
l=[1,3,2,5,54]
a=np.array(l)
print(a)

[ 1  3  2  5 54]


In [ ]:
from numpy import*
a=array([1,2,3,4,5])
print(a)
a=linspace(0,10,5)
print(a)
a=logspace(1,4,4)
print(a)
print(arange(1,10,2))
a=arange(2,10,2)
print(a)
print(zeros(5,int))
print(ones(5,int))
a=array([1,2,3])
print(sin(a))
print(cos(a))
print(tan(a))
print(arcsin(a))
print(log(a))
print(abs(a))
print(sqrt(a))
print(power(a,2))
print(exp(a))
print(sum(a) )
print(a[0])
print(a[0:2])


[1 2 3 4 5]
[ 0.   2.5  5.   7.5 10. ]
[   10.   100.  1000. 10000.]
[1 3 5 7 9]
[2 4 6 8]
[0 0 0 0 0]
[1 1 1 1 1]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]
[1.57079633        nan        nan]
[0.         0.69314718 1.09861229]
[1 2 3]
[1.         1.41421356 1.73205081]
[1 4 9]
[ 2.71828183  7.3890561  20.08553692]
6
1
[1 2]


<ipython-input-43-5c8b58e27150>:17: RuntimeWarning: invalid value encountered in arcsin
  print(arcsin(a))


In [ ]:
a=array([1,2,3,4,5,6,7,8])
print(a)
print(a[3:]

[1 2 3 4 5 6 7 8]
[4]
[[1 2 3]
 [4 5 6]]
6


function


In [ ]:
def  sum(a,b):
  return a+b
print(sum(2,4))

6


odd_even


In [ ]:
def odd_even(a):
  if a%2==0:
    return "even"
  else:
    return "odd"
print(odd_even(4))

even


positive or negative

In [ ]:
def pos(a):
  if a>0:
    return "po"
  elif a==0:
    return "zero"
  else:
    return "ne"
print(pos(5))

po


In [ ]:
def display(str):
  def message():
    return 'how r u ?'
  result = message()+str
  return result
a="hii"
a=display(a)
print(a)

how r u ?hii


In [ ]:
def display(fun):
  return 'welcome' + fun()

def message():
  return ' Iam hajira '
print(display(message))


welcome Iam hajira 


In [ ]:
def display():
  def message():
    return 'how r u ?'
  return message()
#fun refers to the name:message.
fun = display()
print(fun)

how r u ?


In [ ]:
def va(a,*b):
  s=a+sum(*b)
  return s
print(va(10,1,3,5))

TypeError: sum() takes 2 positional arguments but 3 were given

In [ ]:
def my_function(arg1, arg2, *args):
  print("First argument:", arg1)
  print("Second argument:", arg2)
  print("Remaining arguments:")
  for arg in args:
    print(arg)

my_function(1, 2, 3, 4, 5)

First argument: 1
Second argument: 2
Remaining arguments:
3
4
5


local and global variables

In [ ]:
x = 10
y=10
def my_function():
  # Local variable
  y = 5
  print(x)  # Accessing global variable
  print(y)  # Accessing local variable

my_function()
y=17
print(y)

10
5
17


In [ ]:
a=1
def lo():
  a=2
  x=globals()['a']
  print(x)
  print(a)
lo()
print(a)

1
2
1


recursion

In [ ]:
def fact(n):
  if n==1:
    return 1
  else:
    return n*fact(n-1)
print(fact(5))



In [ ]:
def decor(fun):
  def inner():
    value=fun()
    return value+2
  return inner
def num():
  return 10
@decor
a=decor(num)
print(a)

SyntaxError: invalid syntax (<ipython-input-49-71d0fd93779e>, line 9)

In [ ]:
def simple_generator():
    yield 1
    yield 2
    yield 3

# Create a generator object
gen = simple_generator()

# Iterate through the generator
for value in gen:
    print(value)

1
2
3


In [ ]:
def gen(m,n):
  #yield m
  while (m<=n):
    print(m)
    m=m+1
gen(10,20)

10
11
12
13
14
15
16
17
18
19
20


In [ ]:
a=lambda x:x
print(a(10))

10


In [ ]:
squares = [(lambda x: x**2)(x) for x in range(10)]

print(squares)

SyntaxError: invalid syntax (<ipython-input-61-b74433b797ac>, line 1)

encapsulation


In [ ]:
class Car:
  def __init__(self, make, model, year):
    self.__make = make  # Private attribute
    self.__model = model  # Private attribute
    self.__year = year  # Private attribute

  def get_make(self):
    return self.__make

  def set_make(self, make):
    self.__make = make

  def display_info(self):
    print("Car Information:")
    print("Make:", self.get_make())
    print("Model:", self.__model)
    print("Year:", self.__year)

my_car = Car("Toyota", "Corolla", 2022)
my_car.display_info()
my_car.set_make("Honda")
my_car.display_info()

Car Information:
Make: Toyota
Model: Corolla
Year: 2022
Car Information:
Make: Honda
Model: Corolla
Year: 2022


inheritance


In [ ]:
class Animal:
  def __init__(self, name):
    self.name = name

  def speak(self):
    print("Animal sound")

class Dog(Animal):
  def __init__(self, name, breed):
    super().__init__(name)
    self.breed = breed

  def speak(self):
    print("Woof!")

class Cat(Animal):
  def __init__(self, name, color):
    super().__init__(name)
    self.color = color

  def speak(self):
    print("Meow!")

# Create instances of the classes
animal = Animal("Generic Animal")
dog = Dog("Buddy", "Golden Retriever")
cat = Cat("Whiskers", "Tabby")

# Call the speak method on each object
animal.speak()  # Output: Animal sound
dog.speak()     # Output: Woof!
cat.speak()

In [ ]:
class Animal:
  def speak(self):
    print("Animal sound")

class Dog(Animal):
  def speak(self):
    print("Woof!")

class Cat(Animal):
  def speak(self):
    print("Meow!")

# Create instances of the classes
animal = Animal()
dog = Dog()
cat = Cat()

# Call the speak method on each object
animal.speak()  # Output: Animal sound
dog.speak()     # Output: Woof!
cat.speak()